export const Users = [
	{
		id: 1,
		profilePicture: "assets/person/1.jpeg",
		username: "Momo Station",
	},
	{
		id: 2,
		profilePicture: "assets/person/2.jpeg",
		username: " Furniture emporium!",
	},
	{
		id: 3,
		profilePicture: "assets/person/3.jpeg",
		username: "Madhuram",
	},
	{
		id: 4,
		profilePicture: "assets/person/4.jpeg",
		username: "Tinku's",
	},
	{
		id: 5,
		profilePicture: "assets/person/5.jpeg",
		username: "Nafees Restaurant",
	},
	{
		id: 6,
		profilePicture: "assets/person/6.jpeg",
		username: "Hotel Imperial",
	},
	{
		id: 7,
		profilePicture: "assets/person/7.jpeg",
		username: "Momo station(Gita Bhawan)",
	},
	{
		id: 8,
		profilePicture: "assets/person/8.jpeg",
		username: "Ram Kirana Stores",
	},
	{
		id: 9,
		profilePicture: "assets/person/9.jpeg",
		username: "Havour Icecream",
	},
	{
		id: 10,
		profilePicture: "assets/person/10.jpeg",
		username: "GuruKripa",
	},
];

export const Posts = [
	{
		id: 1,
		desc: " We're on the lookout for an employee to join us !!! Your responsibilities will include preparing fillings, folding momos with precision, and ensuring each plate that leaves the kitchen is a masterpiece.#MomoStationHiring ",
		photo: "assets/post/1.jpeg",
		date: "5 mins ago",
		userId: 1,
		like: 32,
		comment: 9,
	},
	{
		id: 2,
		desc: "Explore our exquisite furniture collection at Furniture emporium! We have high-quality and beautifully crafted furniture.We are finding some Wood supplier to work on it.",
		photo: "assets/post/2.jpeg",
		date: "15 mins ago",
		userId: 2,
		like: 2,
		comment: 1,
	},
	{
		id: 3,
		desc: "Join our team at Madhuram! Be a part of creating delicious sandwiches and delivering joy to our customers.We have urgent need of any supplier.",
		photo: "assets/post/3.jpeg",
		date: "1 hour ago",
		userId: 3,
		like: 61,
		comment: 2,
	},
	{
		id: 4,
		photo: "assets/post/4.jpeg",
		date: "4 hours ago",
		userId: 4,
		like: 7,
		comment: 3,
	},
	{
		id: 5,
		photo: "assets/post/5.jpeg",
		date: "5 hours ago",
		userId: 5,
		like: 23,
		comment: 5,
	},
	{
		id: 6,
		photo: "assets/post/6.jpeg",
		date: "1 day ago",
		userId: 6,
		like: 44,
		comment: 6,
	},
	{
		id: 7,
		desc: "",
		photo: "assets/post/7.jpeg",
		date: "2 days ago",
		userId: 7,
		like: 52,
		comment: 3,
	},
	{
		id: 8,
		photo: "assets/post/8.jpeg",
		date: "3 days ago",
		userId: 8,
		like: 15,
		comment: 1,
	},
	{
		id: 9,
		desc: "Explore our exquisite ! We have good quality Icecream.We are finding some supplier to work on it.",
		photo: "assets/post/9.jpeg",
		date: "5 days ago",
		userId: 9,
		like: 11,
		comment: 2,
	},
	{
		id: 10,
		photo: "assets/post/10.jpeg",
		desc: "Join our team at GuruKripa! Be a part of creating delicious and delivering joy to our customers.We have urgent need of any supplier.",
		date: "1 week ago",
		userId: 10,
		like: 104,
		comment: 12,
	},
];
